export const leads=[
    {
        id: 1,
        name: "Rohan",
        email: "roro@gmail.com",
        createdBy: "Shivam",
        technology: "Front End",
        source: "Linked In",
        startDate: "2023-02-04",
        followUpDate: "2023-02-06",
        budget: "5000",
        status: "Active",
        deal: "Hot",
    },
    {
        id: 2,
        name: "Jhaminder",
        email: "jh890@gmail.com",
        createdBy: "Robin",
        technology: "Front End",
        source: "Site",
        startDate: "2023-01-24",
        followUpDate: "2023-02-15",
        budget: "30000",
        status: "Active",
        deal: "Cold",
    },
    {
        id: 3,
        name: "Kapil",
        email: "kp890@gmail.com",
        createdBy: "Shivam",
        technology: "Front End",
        source: "Newspaper",
        startDate: "2023-01-13",
        followUpDate: "2023-02-23",
        budget: "600000",
        status: "Active",
        deal: "Cold",
    },
    {
        id: 4,
        name: "Tarun",
        email: "kp890@gmail.com",
        createdBy: "Robin",
        technology: "Back End",
        source: "Newspaper",
        startDate: "2023-01-30",
        followUpDate: "2023-02-18",
        budget: "6000000",
        status: "Active",
        deal: "Cold",
    },
]


export const followUp=[
    {
        clientName: "Rohan",
        currentDate: "2023-02-04",
        nextFollowUpDate: "2023-02-06",
        comment:"jddfksfjs djkasdjasd jdanskdn",
        status:"Active",
        deal: "Hot",
    },
    {
        clientName: "Rohan",
        currentDate: "2023-02-04",
        nextFollowUpDate: "2023-02-06",
        comment:"jddfksfjs djkasdjasd jdanskdn",
        status: "Active",
        deal: "Hot",
    },
    {
        clientName: "Rohan",
        currentDate: "2023-02-04",
        nextFollowUpDate: "2023-02-06",
        comment:"jddfksfjs djkasdjasd jdanskdn",
        status: "Active",
        deal: "Hot",
    },
    {
        clientName: "Jhaminder",
        currentDate: "2023-02-04",
        nextFollowUpDate: "2023-02-06",
        comment:"jddfksfjs djkasdjasd jdanskdn",
        status: "Active",
        deal: "Hot",
    },
    {
        clientName: "Jhaminder",
        currentDate: "2023-02-04",
        nextFollowUpDate: "2023-02-06",
        comment:"jddfksfjs djkasdjasd jdanskdn",
        status: "Active",
        deal: "Hot",
    },
    {
        clientName: "Kapil",
        currentDate: "2023-02-04",
        nextFollowUpDate: "2023-02-06",
        comment:"jddfksfjs djkasdjasd jdanskdn",
        status: "Active",
        deal: "Hot",
    },
    {
        clientName: "Tarun",
        currentDate: "2023-02-04",
        nextFollowUpDate: "2023-02-06",
        comment:"jddfksfjs djkasdjasd jdanskdn",
        status: "Active",
        deal: "Hot",
    },  
]

export const leadDetails =[
    {  
    name:"Rohan",
    contactNumber:"9867773233",
    email:"roro@gmail.com",
    technology:"Front End",
    budget:"5000",
    source:"Linked In",
    pinCode:"141426",
    stateName:"Uttrakhand",
    cityName:"Dehradun",
    countryName:{text:"India",value:"IN"},
    followUpDate:"2023-02-06",
    createdBy:"Shivam",
    commentGiven:"sahdashjdsva"
    },
    {
        name: "Jhaminder",
        email: "jh890@gmail.com",
        createdBy: "Robin",
        contactNumber:"9867589765",
        technology: "Front End",
        source: "Site",
        followUpDate: "2023-02-15",
        budget: "30000",
        commentGiven:"sahdjha sdjdhda",
        pinCode:"234126",
        stateName:"Uttrakhand",
        cityName:"Gurgaon",
        countryName:{text:"India",value:"IN"},
    },
    {
        name: "Kapil",
        email: "kp890@gmail.com",
        createdBy: "Shivam",
        contactNumber:"9833449765",
        technology: "Front End",
        source: "Newspaper",
        followUpDate: "2023-02-23",
        budget: "600000",
        pinCode:"234126",
        stateName:"Uttrakhand",
        cityName:"Gurgaon",
        countryName:{text:"India",value:"IN"},
        commentGiven:"this is good"
    },
    {
        name: "Tarun",
        email: "kp890@gmail.com",
        createdBy: "Robin",
        contactNumber:"9777589765",
        technology: "Back End",
        source: "Newspaper",
        followUpDate: "2023-02-18",
        budget: "6000000",
        pinCode:"234126",
        stateName:"Maharashtra",
        cityName:"Gurgaon",
        countryName:{text:"India",value:"IN"},
        commentGiven:"good"
    },
 ]