export const leads=[
    {
        id: 1,
        name: "Rohan",
        email: "roro@gmail.com",
        createdBy: "Shivam",
        technology: "React",
        source: "Linked In",
        startDate: "2023-02-04",
        followUpDate: "2023-02-06",
        budget: "5000",
        status: "Active",
        deal: "Hot",
    },
    {
        id: 2,
        name: "Jhaminder",
        email: "jh890@gmail.com",
        createdBy: "Robin",
        technology: "Angular",
        source: "Site",
        startDate: "2023-01-24",
        followUpDate: "2023-02-15",
        budget: "30000",
        status: "Active",
        deal: "Cold",
    },
    {
        id: 3,
        name: "kapil",
        email: "kp890@gmail.com",
        createdBy: "Shivam",
        technology: "React",
        source: "Newspaper",
        startDate: "2023-01-13",
        followUpDate: "2023-02-23",
        budget: "600000",
        status: "Active",
        deal: "Cold",
    },
    {
        id: 4,
        name: "Tarun",
        email: "kp890@gmail.com",
        createdBy: "Robin",
        technology: "Node",
        source: "Newspaper",
        startDate: "2023-01-30",
        followUpDate: "2023-02-18",
        budget: "6000000",
        status: "Active",
        deal: "Cold",
    },
]


export const followUp=[
    {
        id: 1,
        clientName: "Rohan",
        currentDate: "2023-02-04",
        nextFollowUpDate: "2023-02-06",
        comment:"jddfksfjs djkasdjasd jdanskdn",
        status:"Active",
        deal: "Hot",
    },
    {
        id: 2,
        clientName: "Rohan",
        currentDate: "2023-02-04",
        nextFollowUpDate: "2023-02-06",
        comment:"jddfksfjs djkasdjasd jdanskdn",
        status: "Active",
        deal: "Hot",
    },
    {
        id: 3,
        clientName: "Rohan",
        currentDate: "2023-02-04",
        nextFollowUpDate: "2023-02-06",
        comment:"jddfksfjs djkasdjasd jdanskdn",
        status: "Active",
        deal: "Hot",
    },
    {
        id: 4,
        clientName: "Jim",
        currentDate: "2023-02-04",
        nextFollowUpDate: "2023-02-06",
        comment:"jddfksfjs djkasdjasd jdanskdn",
        status: "Active",
        deal: "Hot",
    },
    {
        id: 5,
        clientName: "Jim",
        currentDate: "2023-02-04",
        nextFollowUpDate: "2023-02-06",
        comment:"jddfksfjs djkasdjasd jdanskdn",
        status: "Active",
        deal: "Hot",
    },
    {
        id:6,
        clientName: "Tim",
        currentDate: "2023-02-04",
        nextFollowUpDate: "2023-02-06",
        comment:"jddfksfjs djkasdjasd jdanskdn",
        status: "Active",
        deal: "Hot",
    },
    {
        id: 7,
        clientName: "Rim",
        currentDate: "2023-02-04",
        nextFollowUpDate: "2023-02-06",
        comment:"jddfksfjs djkasdjasd jdanskdn",
        status: "Active",
        deal: "Hot",
    },  
]