export let CouponData = [
    {
        Country: "India",
        Title: "Super Off",
        Code: "KMDR214K",
        couponType: "fixed",
        CustomerId: "",
        startDate: "28-11-2022",
        endDate: "10-12-2022",
        quotaPerUser: "10",
        firstTimeUser: true,
        maxDiscountAmount: " 85",
        miniBillAmount: "800",
        status:true,
        discount: "85",
        date: "28-11-2022",
        description: "Save upto  Rs 85",
    },
    {
        Country: "India",
        Title: "Super Off",
        Code: "KMD5214K",
        couponType: "fixed",
        CustomerId: "",
        startDate: "28-11-2022",
        endDate: "10-12-2022",
        quotaPerUser: "2",
        status:true,
        firstTimeUser: false,
        maxDiscountAmount: " 98",
        miniBillAmount: "900",
        discount: "98",
        date: "28-11-2022",
        description: "Save upto  Rs 98",
    },
    {
        Country: "India",
        Title: "Super Off",
        Code: "PMDR214K",
        couponType: "fixed",
        CustomerId: "",
        startDate: "28-11-2022",
        status:true,
        endDate: "10-12-2022",
        quotaPerUser: "5",
        firstTimeUser: true,
        maxDiscountAmount: " 105",
        miniBillAmount: "800",
        discount: "105",
        date: "28-11-2022",
        description: "Save upto  Rs 105",
    },
    {
        Country: "India",
        Title: "Super Off",
        Code: "SQMDR214K",
        couponType: "percentage",
        CustomerId: "",
        startDate: "28-11-2022",
        endDate: "10-12-2022",
        quotaPerUser: "5",
        status:true,
        firstTimeUser: false,
        maxDiscountAmount: " 125",
        miniBillAmount: "1000",
        discount: "25",
        date: "28-11-2022",
        description: "Save upto  Rs 125",
    },
    {
        Country: "India",
        Title: "Super Off",
        Code: "ASWDR214K",
        couponType: "percentage",
        CustomerId: "",
        startDate: "28-11-2022",
        endDate: "10-12-2022",
        quotaPerUser: "5",
        status:true,
        firstTimeUser: false,
        maxDiscountAmount: " 200",
        miniBillAmount: "1000",
        discount: "25",
        date: "28-11-2022",
        description: "Save upto  Rs 200",
    }
]