export let CouponData = [
    {
        id: 12,
        Country: "India",
        Title: "Super Off",
        Code: "KMDR214K",
        couponType: "fixed",
        CustomerId: "",
        startDate: "2022-10-10",
        endDate: "2022-10-22",
        quotaPerUser: "10",
        firstTimeUser: true,
        maxDiscountAmount: " 85",
        miniBillAmount: "800",
        status: true,
        discount: "85",
        date: "2022-10-10",
        description: "Save upto  Rs 85",
    },
    {
        id: 233,
        Country: "India",
        Title: "Super Off",
        Code: "KMD5214K",
        couponType: "fixed",
        CustomerId: "",
        startDate: "2022-10-22",
        endDate: "2022-11-12",
        quotaPerUser: "2",
        status: true,
        firstTimeUser: false,
        maxDiscountAmount: " 98",
        miniBillAmount: "900",
        discount: "98",
        date: "2022-10-22",
        description: "Save upto  Rs 98",
    },
    {
        id: 234,
        Country: "India",
        Title: "Super Off",
        Code: "PMDR214K",
        couponType: "fixed",
        CustomerId: "",
        startDate: "2022-11-28",
        status: true,
        endDate: "2022-12-10",
        quotaPerUser: "5",
        firstTimeUser: true,
        maxDiscountAmount: " 105",
        miniBillAmount: "800",
        discount: "105",
        date: "2022-11-28",
        description: "Save upto  Rs 105",
    },
    {
        id: 235,
        Country: "India",
        Title: "Super Off",
        Code: "SQMDR214K",
        couponType: "percentage",
        CustomerId: "",
        startDate: "2022-11-28",
        endDate: "2022-12-28",
        quotaPerUser: "5",
        status: true,
        firstTimeUser: false,
        maxDiscountAmount: " 125",
        miniBillAmount: "1000",
        discount: "25",
        date: "2022-11-28",
        description: "Save upto  Rs 125",
    },
    {
        id: 236,
        Country: "India",
        Title: "Super Off",
        Code: "ASWDR214K",
        couponType: "percentage",
        CustomerId: "",
        startDate: "2022-09-12",
        endDate: "2022-10-12",
        quotaPerUser: "5",
        status: true,
        firstTimeUser: false,
        maxDiscountAmount: " 200",
        miniBillAmount: "1000",
        discount: "25",
        date: "2022-09-12",
        description: "Save upto  Rs 200",
    }
]