export let Order = [
    {
        orderId: 1411,
        customerId: '1053',
        orderDate: "12/11/2022",
        orderNo: "DSR1452268",
        paymentStatus: "pending",
        deliveryType: "standard",
        paymentType: "Cash",
        total: "$1452.14",
        deliveryStatus: "Inprogress",
        orderStatus:"Confirmed",
        country: "India",
        email: "aryaveer@gmail.com",
        mobileNo: "9453693219",
        Billing_address:{
            billingPinCode: "121",
            billingFlatNo: "223",
            billingHouseNo:"33",
            billingBuildingName: "gayle tower",
            billingApartmentName: "GT",
            billingArea: "WWW",
            billingStreetName: "NZ",
            billingSectorName: "dd231",
            billingVillageName: "frdg",
            billingLandmark: "564",
            billingCity: "dddddcv",
            billingTown: "gSDgsheh",

        },
        Shipping_address:{
            shippingPinCode: "2314",
            shippingFlatNo: "666",
            shippingHouseNo: "1234",
            shippingBuildingName:"reh platina",
            shippingApartmentName: "frtjh",
            shippingArea: "dd",
            shippingStreetName: "dfdshe",
            shippingSectorName: "1345",
            shippingVillageName: "zhdfdjn",
            shippingLandmark: "nng",
            shippingCity: "gnmg",
            shippingTown: "ngg",
          },
        },
    {
        orderId: 1412,
        customerId: '1063',
        orderDate: "15/11/2022",
        orderNo: "DSR145268",
        paymentStatus: "pending",
        deliveryType: "standard",
        paymentType: "Card",
        total: "$142.14",
        deliveryStatus: "Delivered",
        orderStatus:"Confirmed",
        country: "India",
        email: "aryaveer@gmail.com",
        mobileNo: "9453693219",
        Billing_address:{
            billingPinCode: "121",
            billingFlatNo: "223",
            billingHouseNo:"33",
            billingBuildingName: "gayle tower",
            billingApartmentName: "GT",
            billingArea: "WWW",
            billingStreetName: "NZ",
            billingSectorName: "dd231",
            billingVillageName: "frdg",
            billingLandmark: "564",
            billingCity: "dddddcv",
            billingTown: "gSDgsheh",

        },
        Shipping_address:{
            shippingPinCode: "2314",
            shippingFlatNo: "666",
            shippingHouseNo: "1234",
            shippingBuildingName:"reh platina",
            shippingApartmentName: "frtjh",
            shippingArea: "dd",
            shippingStreetName: "dfdshe",
            shippingSectorName: "1345",
            shippingVillageName: "zhdfdjn",
            shippingLandmark: "nng",
            shippingCity: "gnmg",
            shippingTown: "ngg",
          },
    },
    {
        orderId: 1413,
        customerId: '1063',
        orderDate: "15/11/2022",
        orderNo: "DSR145268",
        paymentStatus: "pending",
        deliveryType: "standard",
        paymentType: "Card",
        total: "$142.14",
        deliveryStatus: "Delivered",
        orderStatus:"Confirmed",
        country: "India",
        email: "aryaveer@gmail.com",
        mobileNo: "9453693219",
        Billing_address:{
            billingPinCode: "121",
            billingFlatNo: "223",
            billingHouseNo:"33",
            billingBuildingName: "gayle tower",
            billingApartmentName: "GT",
            billingArea: "WWW",
            billingStreetName: "NZ",
            billingSectorName: "dd231",
            billingVillageName: "frdg",
            billingLandmark: "564",
            billingCity: "dddddcv",
            billingTown: "gSDgsheh",

        },
        Shipping_address:{
            shippingPinCode: "2314",
            shippingFlatNo: "666",
            shippingHouseNo: "1234",
            shippingBuildingName:"reh platina",
            shippingApartmentName: "frtjh",
            shippingArea: "dd",
            shippingStreetName: "dfdshe",
            shippingSectorName: "1345",
            shippingVillageName: "zhdfdjn",
            shippingLandmark: "nng",
            shippingCity: "gnmg",
            shippingTown: "ngg",
          },
    },
    {
        orderId: 1414,
        customerId: '1063',
        orderDate: "15/11/2022",
        orderNo: "DSR145268",
        paymentStatus: "pending",
        deliveryType: "standard",
        paymentType: "Card",
        total: "$142.14",
        deliveryStatus: "Delivered",
        orderStatus:"Confirmed",
        country: "India",
        email: "aryaveer@gmail.com",
        mobileNo: "9453693219",
        Billing_address:{
            billingPinCode: "121",
            billingFlatNo: "223",
            billingHouseNo:"33",
            billingBuildingName: "gayle tower",
            billingApartmentName: "GT",
            billingArea: "WWW",
            billingStreetName: "NZ",
            billingSectorName: "dd231",
            billingVillageName: "frdg",
            billingLandmark: "564",
            billingCity: "dddddcv",
            billingTown: "gSDgsheh",

        },
        Shipping_address:{
            shippingPinCode: "2314",
            shippingFlatNo: "666",
            shippingHouseNo: "1234",
            shippingBuildingName:"reh platina",
            shippingApartmentName: "frtjh",
            shippingArea: "dd",
            shippingStreetName: "dfdshe",
            shippingSectorName: "1345",
            shippingVillageName: "zhdfdjn",
            shippingLandmark: "nng",
            shippingCity: "gnmg",
            shippingTown: "ngg",
          },
        },
    {
        orderId: 1422,
        customerId: '1063',
        orderDate: "15/11/2022",
        orderNo: "DSR145268",
        paymentStatus: "pending",
        deliveryType: "standard",
        paymentType: "Card",
        total: "$142.14",
        deliveryStatus: "Delivered",
        orderStatus:"Confirmed",
        country: "India",
        email: "aryaveer@gmail.com",
        mobileNo: "9453693219",
        Billing_address:{
            billingPinCode: "121",
            billingFlatNo: "223",
            billingHouseNo:"33",
            billingBuildingName: "gayle tower",
            billingApartmentName: "GT",
            billingArea: "WWW",
            billingStreetName: "NZ",
            billingSectorName: "dd231",
            billingVillageName: "frdg",
            billingLandmark: "564",
            billingCity: "dddddcv",
            billingTown: "gSDgsheh",

        },
        Shipping_address:{
            shippingPinCode: "2314",
            shippingFlatNo: "666",
            shippingHouseNo: "1234",
            shippingBuildingName:"reh platina",
            shippingApartmentName: "frtjh",
            shippingArea: "dd",
            shippingStreetName: "dfdshe",
            shippingSectorName: "1345",
            shippingVillageName: "zhdfdjn",
            shippingLandmark: "nng",
            shippingCity: "gnmg",
            shippingTown: "ngg",
          },
        },
    {
        orderId: 1358,
        customerId: '1033',
        orderDate: "20/11/2022",
        orderNo: "DSR14500268",
        paymentStatus: "paid",
        deliveryType: "standard",
        paymentType: "Cash",
        total: "$1482.14",
        deliveryStatus: "Inprogress",
        orderStatus:"Confirmed",
        country: "India",
        email: "aryaveer@gmail.com",
        mobileNo: "9453693219",
        Billing_address:{
            billingPinCode: "121",
            billingFlatNo: "223",
            billingHouseNo:"33",
            billingBuildingName: "gayle tower",
            billingApartmentName: "GT",
            billingArea: "WWW",
            billingStreetName: "NZ",
            billingSectorName: "dd231",
            billingVillageName: "frdg",
            billingLandmark: "564",
            billingCity: "dddddcv",
            billingTown: "gSDgsheh",

        },
        Shipping_address:{
            shippingPinCode: "2314",
            shippingFlatNo: "666",
            shippingHouseNo: "1234",
            shippingBuildingName:"reh platina",
            shippingApartmentName: "frtjh",
            shippingArea: "dd",
            shippingStreetName: "dfdshe",
            shippingSectorName: "1345",
            shippingVillageName: "zhdfdjn",
            shippingLandmark: "nng",
            shippingCity: "gnmg",
            shippingTown: "ngg",
          },
        },
    {
        orderId: 1123,
        customerId: '1083',
        orderDate: "25/11/2022",
        orderNo: "DSR14511268",
        paymentStatus: "paid",
        deliveryType: "standard",
        paymentType: "UPI",
        total: "$1282.14",
        deliveryStatus: "Inprogress",
        orderStatus:"Confirmed",
        country: "India",
        email: "aryaveer@gmail.com",
        mobileNo: "9453693219",
        Billing_address:{
            billingPinCode: "121",
            billingFlatNo: "223",
            billingHouseNo:"33",
            billingBuildingName: "gayle tower",
            billingApartmentName: "GT",
            billingArea: "WWW",
            billingStreetName: "NZ",
            billingSectorName: "dd231",
            billingVillageName: "frdg",
            billingLandmark: "564",
            billingCity: "dddddcv",
            billingTown: "gSDgsheh",

        },
        Shipping_address:{
            shippingPinCode: "2314",
            shippingFlatNo: "666",
            shippingHouseNo: "1234",
            shippingBuildingName:"reh platina",
            shippingApartmentName: "frtjh",
            shippingArea: "dd",
            shippingStreetName: "dfdshe",
            shippingSectorName: "1345",
            shippingVillageName: "zhdfdjn",
            shippingLandmark: "nng",
            shippingCity: "gnmg",
            shippingTown: "ngg",
          },
        },
    {
        orderId: 1455,
        customerId: '1073',
        orderDate: "20/11/2022",
        orderNo: "DSR14500268",
        paymentStatus: "paid",
        deliveryType: "standard",
        paymentType: "Card",
        total: "$1482.14",
        deliveryStatus: "Inprogress",
        orderStatus:"Confirmed",
        country: "India",
        email: "aryaveer@gmail.com",
        mobileNo: "9453693219",
        Billing_address:{
            billingPinCode: "121",
            billingFlatNo: "223",
            billingHouseNo:"33",
            billingBuildingName: "gayle tower",
            billingApartmentName: "GT",
            billingArea: "WWW",
            billingStreetName: "NZ",
            billingSectorName: "dd231",
            billingVillageName: "frdg",
            billingLandmark: "564",
            billingCity: "dddddcv",
            billingTown: "gSDgsheh",

        },
        Shipping_address:{
            shippingPinCode: "2314",
            shippingFlatNo: "666",
            shippingHouseNo: "1234",
            shippingBuildingName:"reh platina",
            shippingApartmentName: "frtjh",
            shippingArea: "dd",
            shippingStreetName: "dfdshe",
            shippingSectorName: "1345",
            shippingVillageName: "zhdfdjn",
            shippingLandmark: "nng",
            shippingCity: "gnmg",
            shippingTown: "ngg",
          },
        },
    {
        orderId: 1258,
        customerId: '1073',
        orderDate: "20/11/2022",
        orderNo: "DSR14500268",
        paymentStatus: "paid",
        deliveryType: "standard",
        paymentType: "Card",
        total: "$1482.14",
        deliveryStatus: "Confirmed",
        orderStatus:"Confirmed",
        country: "India",
        email: "aryaveer@gmail.com",
        mobileNo: "9453693219",
        Billing_address:{
            billingPinCode: "121",
            billingFlatNo: "223",
            billingHouseNo:"33",
            billingBuildingName: "gayle tower",
            billingApartmentName: "GT",
            billingArea: "WWW",
            billingStreetName: "NZ",
            billingSectorName: "dd231",
            billingVillageName: "frdg",
            billingLandmark: "564",
            billingCity: "dddddcv",
            billingTown: "gSDgsheh",

        },
        Shipping_address:{
            shippingPinCode: "2314",
            shippingFlatNo: "666",
            shippingHouseNo: "1234",
            shippingBuildingName:"reh platina",
            shippingApartmentName: "frtjh",
            shippingArea: "dd",
            shippingStreetName: "dfdshe",
            shippingSectorName: "1345",
            shippingVillageName: "zhdfdjn",
            shippingLandmark: "nng",
            shippingCity: "gnmg",
            shippingTown: "ngg",
          },
        },
    {
        orderId: 1258,
        customerId: '1073',
        orderDate: "20/11/2022",
        orderNo: "DSR14500268",
        paymentStatus: "paid",
        deliveryType: "standard",
        paymentType: "Card",
        total: "$1482.14",
        deliveryStatus: "Confirmed",
        orderStatus:"Confirmed",
        country: "India",
        email: "aryaveer@gmail.com",
        mobileNo: "9453693219",
        Billing_address:{
            billingPinCode: "121",
            billingFlatNo: "223",
            billingHouseNo:"33",
            billingBuildingName: "gayle tower",
            billingApartmentName: "GT",
            billingArea: "WWW",
            billingStreetName: "NZ",
            billingSectorName: "dd231",
            billingVillageName: "frdg",
            billingLandmark: "564",
            billingCity: "dddddcv",
            billingTown: "gSDgsheh",

        },
        Shipping_address:{
            shippingPinCode: "2314",
            shippingFlatNo: "666",
            shippingHouseNo: "1234",
            shippingBuildingName:"reh platina",
            shippingApartmentName: "frtjh",
            shippingArea: "dd",
            shippingStreetName: "dfdshe",
            shippingSectorName: "1345",
            shippingVillageName: "zhdfdjn",
            shippingLandmark: "nng",
            shippingCity: "gnmg",
            shippingTown: "ngg",
          },
        },
    {
        orderId: 1258,
        customerId: '1073',
        orderDate: "20/11/2022",
        orderNo: "DSR14500268",
        paymentStatus: "paid",
        deliveryType: "standard",
        paymentType: "Card",
        total: "$1482.14",
        deliveryStatus: "Confirmed",
        orderStatus:"Confirmed",
        country: "India",
        email: "aryaveer@gmail.com",
        mobileNo: "9453693219",
        Billing_address:{
            billingPinCode: "121",
            billingFlatNo: "223",
            billingHouseNo:"33",
            billingBuildingName: "gayle tower",
            billingApartmentName: "GT",
            billingArea: "WWW",
            billingStreetName: "NZ",
            billingSectorName: "dd231",
            billingVillageName: "frdg",
            billingLandmark: "564",
            billingCity: "dddddcv",
            billingTown: "gSDgsheh",

        },
        Shipping_address:{
            shippingPinCode: "2314",
            shippingFlatNo: "666",
            shippingHouseNo: "1234",
            shippingBuildingName:"reh platina",
            shippingApartmentName: "frtjh",
            shippingArea: "dd",
            shippingStreetName: "dfdshe",
            shippingSectorName: "1345",
            shippingVillageName: "zhdfdjn",
            shippingLandmark: "nng",
            shippingCity: "gnmg",
            shippingTown: "ngg",
          },
        },
    {
        orderId: 1258,
        customerId: '1073',
        orderDate: "20/11/2022",
        orderNo: "DSR14500268",
        paymentStatus: "paid",
        deliveryType: "standard",
        paymentType: "Card",
        total: "$1482.14",
        deliveryStatus: "Confirmed",
        orderStatus:"Confirmed",
        country: "India",
        email: "aryaveer@gmail.com",
        mobileNo: "9453693219",
        Billing_address:{
            billingPinCode: "121",
            billingFlatNo: "223",
            billingHouseNo:"33",
            billingBuildingName: "gayle tower",
            billingApartmentName: "GT",
            billingArea: "WWW",
            billingStreetName: "NZ",
            billingSectorName: "dd231",
            billingVillageName: "frdg",
            billingLandmark: "564",
            billingCity: "dddddcv",
            billingTown: "gSDgsheh",

        },
        Shipping_address:{
            shippingPinCode: "2314",
            shippingFlatNo: "666",
            shippingHouseNo: "1234",
            shippingBuildingName:"reh platina",
            shippingApartmentName: "frtjh",
            shippingArea: "dd",
            shippingStreetName: "dfdshe",
            shippingSectorName: "1345",
            shippingVillageName: "zhdfdjn",
            shippingLandmark: "nng",
            shippingCity: "gnmg",
            shippingTown: "ngg",
          },
        },
    {
        orderId: 1258,
        customerId: '1073',
        orderDate: "20/11/2022",
        orderNo: "DSR14500268",
        paymentStatus: "paid",
        deliveryType: "standard",
        paymentType: "Card",
        total: "$1482.14",
        deliveryStatus: "Confirmed",
        orderStatus:"Confirmed",
        country: "India",
        email: "aryaveer@gmail.com",
        mobileNo: "9453693219",
        Billing_address:{
            billingPinCode: "121",
            billingFlatNo: "223",
            billingHouseNo:"33",
            billingBuildingName: "gayle tower",
            billingApartmentName: "GT",
            billingArea: "WWW",
            billingStreetName: "NZ",
            billingSectorName: "dd231",
            billingVillageName: "frdg",
            billingLandmark: "564",
            billingCity: "dddddcv",
            billingTown: "gSDgsheh",

        },
        Shipping_address:{
            shippingPinCode: "2314",
            shippingFlatNo: "666",
            shippingHouseNo: "1234",
            shippingBuildingName:"reh platina",
            shippingApartmentName: "frtjh",
            shippingArea: "dd",
            shippingStreetName: "dfdshe",
            shippingSectorName: "1345",
            shippingVillageName: "zhdfdjn",
            shippingLandmark: "nng",
            shippingCity: "gnmg",
            shippingTown: "ngg",
          },
        },
]

export let cancelOrder = [
    {
        cancelTransId: 147,
        orderId: 128,
        total: "$1482.14",
        refundInitiated: false,
        productId: [142, 458, 369, 458],
        deliveryCharge: "$8.1"
    },
    {
        cancelTransId: 147,
        orderId: 1258,
        total: "$1482.14",
        refundInitiated: false,
        productId: [142, 458, 369, 458],
        deliveryCharge: "$8.1"
    },
    {
        cancelTransId: 142,
        orderId: 1258,
        total: "$1482.14",
        refundInitiated: false,
        productId: [142, 458, 369, 458],
        deliveryCharge: "$8.1"
    },
    {
        cancelTransId: 171,
        orderId: 1255,
        total: "$1482.14",
        refundInitiated: false,
        productId: [142, 458, 369, 458],
        deliveryCharge: "$8.1"
    }
]
export let orderTransactin = [
    {
        transactionId: "r1548268ef457",
        orderId: 1534,
        productId: [145, 254, 9875,],
        discount: "$4.24",
        deliveryCharge: "$8.125",
        productTotal: "$875.32",
        tax: "$48.45",
        totalAmountWith: "$587.41",
        methodOfPayment: "Cash"
    },
    {
        transactionId: "r1548268ef457",
        orderId: 1504,
        productId: [145, 254, 9875,],
        discount: "$4.24",
        deliveryCharge: "$8.125",
        productTotal: "$875.32",
        tax: "$48.45",
        totalAmountWith: "$587.41",
        methodOfPayment: "UPI"
    },
    {
        transactionId: "r1548268ef457",
        orderId: 1514,
        productId: [145, 254, 9875,],
        discount: "$4.24",
        deliveryCharge: "$8.125",
        productTotal: "$875.32",
        tax: "$48.45",
        totalAmountWith: "$587.41",
        methodOfPayment: "COD"
    },
    {
        transactionId: "r1548268ef457",
        orderId: 1569,
        productId: [145, 254, 9875,],
        discount: "$4.24",
        deliveryCharge: "$8.125",
        productTotal: "$875.32",
        tax: "$48.45",
        totalAmountWith: "$587.41",
        methodOfPayment: "Card"
    }
]
export let orderDetails =[
    {
    orderDetails:{
    order_name: "",
    order_no: "",
    order_status: ""
    },
    customer_details: {
    customer_name:"",
    email:"",
    mobile_no:"",
    },
    shipping_address: {
    name:"",
    mobile_no:"",
    pin_code:"",
    house_no:"",
    Area_street:"",
    landmark:"",
    city:"",
    country:""
    },
    billing_address: {
    name:"",
    mobile_no:"",
    pin_code:"",
    house_no:"",
    Area_street:"",
    landmark:"",
    city:"",
    country:""
    },
    product_details: {
    product_name:"",
    sku:"",
    seller:"",
    price:"",
    quantity:"",
    total:"",
    product_status:""
    },
    order_summary: {
    delivery_instruction:"",
    product_total:"",
    coupon:"",
    discount:"",
    delivery_type:"",
    delivery_charge:"",
    tax_percentage:"",
    tax_amount:"",
    total:""
    },
    payment_details: {
    transaction_method:"",
    mode_payment:"",
    amount:"",
    payment_status:""
    },
    transaction_details: {
    reference_no: "",
    amount:"",
    type:"",
    transcation_date:""
    }
    }
    ]