export let order = [
    {
        orderId: 1458,
        customerId: '1053',
        orderDate: "12/11/2022",
        orderNo: "DSR1452268",
        paymentStatus: "pending",
        deliveryType: "standard",
        paymentType: "Cash",
        total: "$1452.14",
        deliveryStatus: "Inprogress",
        orderStatus:"Confirmed",
        country: "India",
        email: "aryaveer@gmail.com",
        mobileNo: "9453693219",
        billingCityName: "Shivank street",
        billingBuildingName: "plam street",
        billingBlockName: "",
        billingFloorNo: "",
        billingUnit: "",
        billingPostalCode: "",
        billingStreetName: "",
        shippingPostalCode: "",
        shippingCityName: "",
        shippingBuildingName: "",
        shippingBlockName: "",
        shippingFloorNo: "",
        shippingunit: "",
        shippingStreetName: ""
    },
    {
        orderId: 1433,
        customerId: '1063',
        orderDate: "15/11/2022",
        orderNo: "DSR145268",
        paymentStatus: "pending",
        deliveryType: "standard",
        paymentType: "Card",
        total: "$142.14",
        deliveryStatus: "Delivered",
        orderStatus:"Confirmed",
        country: "India",
        email: "aryaveer@gmail.com",
        mobileNo: "9453693219",
        billingCityName: "Shivank street",
        billingBuildingName: "plam street",
        billingBlockName: "",
        billingFloorNo: "",
        billingUnit: "",
        billingPostalCode: "",
        billingStreetName: "",
        shippingPostalCode: "",
        shippingCityName: "",
        shippingBuildingName: "",
        shippingBlockName: "",
        shippingFloorNo: "",
        shippingunit: "",
        shippingStreetName: ""
    },
    {
        orderId: 1438,
        customerId: '1063',
        orderDate: "15/11/2022",
        orderNo: "DSR145268",
        paymentStatus: "pending",
        deliveryType: "standard",
        paymentType: "Card",
        total: "$142.14",
        deliveryStatus: "Delivered",
        orderStatus:"Confirmed",
        country: "India",
        email: "aryaveer@gmail.com",
        mobileNo: "9453693219",
        billingCityName: "Shivank street",
        billingBuildingName: "plam street",
        billingBlockName: "",
        billingFloorNo: "",
        billingUnit: "",
        billingPostalCode: "",
        billingStreetName: "",
        shippingPostalCode: "",
        shippingCityName: "",
        shippingBuildingName: "",
        shippingBlockName: "",
        shippingFloorNo: "",
        shippingunit: "",
        shippingStreetName: ""
    },
    {
        orderId: 1438,
        customerId: '1063',
        orderDate: "15/11/2022",
        orderNo: "DSR145268",
        paymentStatus: "pending",
        deliveryType: "standard",
        paymentType: "Card",
        total: "$142.14",
        deliveryStatus: "Delivered",
        orderStatus:"Confirmed",
        country: "India",
        email: "aryaveer@gmail.com",
        mobileNo: "9453693219",
        billingCityName: "Shivank street",
        billingBuildingName: "plam street",
        billingBlockName: "",
        billingFloorNo: "",
        billingUnit: "",
        billingPostalCode: "",
        billingStreetName: "",
        shippingPostalCode: "",
        shippingCityName: "",
        shippingBuildingName: "",
        shippingBlockName: "",
        shippingFloorNo: "",
        shippingunit: "",
        shippingStreetName: ""
    },
    {
        orderId: 1438,
        customerId: '1063',
        orderDate: "15/11/2022",
        orderNo: "DSR145268",
        paymentStatus: "pending",
        deliveryType: "standard",
        paymentType: "Card",
        total: "$142.14",
        deliveryStatus: "Delivered",
        orderStatus:"Confirmed",
        country: "India",
        email: "aryaveer@gmail.com",
        mobileNo: "9453693219",
        billingCityName: "Shivank street",
        billingBuildingName: "plam street",
        billingBlockName: "",
        billingFloorNo: "",
        billingUnit: "",
        billingPostalCode: "",
        billingStreetName: "",
        shippingPostalCode: "",
        shippingCityName: "",
        shippingBuildingName: "",
        shippingBlockName: "",
        shippingFloorNo: "",
        shippingunit: "",
        shippingStreetName: ""
    },
    {
        orderId: 1358,
        customerId: '1033',
        orderDate: "20/11/2022",
        orderNo: "DSR14500268",
        paymentStatus: "paid",
        deliveryType: "standard",
        paymentType: "Cash",
        total: "$1482.14",
        deliveryStatus: "Inprogress",
        orderStatus:"Confirmed",
        country: "India",
        email: "aryaveer@gmail.com",
        mobileNo: "9453693219",
        billingCityName: "Shivank street",
        billingBuildingName: "plam street",
        billingBlockName: "",
        billingFloorNo: "",
        billingUnit: "",
        billingPostalCode: "",
        billingStreetName: "",
        shippingPostalCode: "",
        shippingCityName: "",
        shippingBuildingName: "",
        shippingBlockName: "",
        shippingFloorNo: "",
        shippingunit: "",
        shippingStreetName: ""
    },
    {
        orderId: 1158,
        customerId: '1083',
        orderDate: "25/11/2022",
        orderNo: "DSR14511268",
        paymentStatus: "paid",
        deliveryType: "standard",
        paymentType: "UPI",
        total: "$1282.14",
        deliveryStatus: "Inprogress",
        orderStatus:"Confirmed",
        country: "India",
        email: "aryaveer@gmail.com",
        mobileNo: "9453693219",
        billingCityName: "Shivank street",
        billingBuildingName: "plam street",
        billingBlockName: "",
        billingFloorNo: "",
        billingUnit: "",
        billingPostalCode: "",
        billingStreetName: "",
        shippingPostalCode: "",
        shippingCityName: "",
        shippingBuildingName: "",
        shippingBlockName: "",
        shippingFloorNo: "",
        shippingunit: "",
        shippingStreetName: ""
    },
    {
        orderId: 1258,
        customerId: '1073',
        orderDate: "20/11/2022",
        orderNo: "DSR14500268",
        paymentStatus: "paid",
        deliveryType: "standard",
        paymentType: "Card",
        total: "$1482.14",
        deliveryStatus: "Inprogress",
        orderStatus:"Confirmed",
        country: "India",
        email: "aryaveer@gmail.com",
        mobileNo: "9453693219",
        billingCityName: "Shivank street",
        billingBuildingName: "plam street",
        billingBlockName: "",
        billingFloorNo: "",
        billingUnit: "",
        billingPostalCode: "",
        billingStreetName: "",
        shippingPostalCode: "",
        shippingCityName: "",
        shippingBuildingName: "",
        shippingBlockName: "",
        shippingFloorNo: "",
        shippingunit: "",
        shippingStreetName: ""
    },
    {
        orderId: 1258,
        customerId: '1073',
        orderDate: "20/11/2022",
        orderNo: "DSR14500268",
        paymentStatus: "paid",
        deliveryType: "standard",
        paymentType: "Card",
        total: "$1482.14",
        deliveryStatus: "Confirmed",
        orderStatus:"Confirmed",
        country: "India",
        email: "aryaveer@gmail.com",
        mobileNo: "9453693219",
        billingCityName: "Shivank street",
        billingBuildingName: "plam street",
        billingBlockName: "",
        billingFloorNo: "",
        billingUnit: "",
        billingPostalCode: "",
        billingStreetName: "",
        shippingPostalCode: "",
        shippingCityName: "",
        shippingBuildingName: "",
        shippingBlockName: "",
        shippingFloorNo: "",
        shippingunit: "",
        shippingStreetName: ""
    },
    {
        orderId: 1258,
        customerId: '1073',
        orderDate: "20/11/2022",
        orderNo: "DSR14500268",
        paymentStatus: "paid",
        deliveryType: "standard",
        paymentType: "Card",
        total: "$1482.14",
        deliveryStatus: "Confirmed",
        orderStatus:"Confirmed",
        country: "India",
        email: "aryaveer@gmail.com",
        mobileNo: "9453693219",
        billingCityName: "Shivank street",
        billingBuildingName: "plam street",
        billingBlockName: "",
        billingFloorNo: "",
        billingUnit: "",
        billingPostalCode: "",
        billingStreetName: "",
        shippingPostalCode: "",
        shippingCityName: "",
        shippingBuildingName: "",
        shippingBlockName: "",
        shippingFloorNo: "",
        shippingunit: "",
        shippingStreetName: ""
    },
    {
        orderId: 1258,
        customerId: '1073',
        orderDate: "20/11/2022",
        orderNo: "DSR14500268",
        paymentStatus: "paid",
        deliveryType: "standard",
        paymentType: "Card",
        total: "$1482.14",
        deliveryStatus: "Confirmed",
        orderStatus:"Confirmed",
        country: "India",
        email: "aryaveer@gmail.com",
        mobileNo: "9453693219",
        billingCityName: "Shivank street",
        billingBuildingName: "plam street",
        billingBlockName: "",
        billingFloorNo: "",
        billingUnit: "",
        billingPostalCode: "",
        billingStreetName: "",
        shippingPostalCode: "",
        shippingCityName: "",
        shippingBuildingName: "",
        shippingBlockName: "",
        shippingFloorNo: "",
        shippingunit: "",
        shippingStreetName: ""
    },
    {
        orderId: 1258,
        customerId: '1073',
        orderDate: "20/11/2022",
        orderNo: "DSR14500268",
        paymentStatus: "paid",
        deliveryType: "standard",
        paymentType: "Card",
        total: "$1482.14",
        deliveryStatus: "Confirmed",
        orderStatus:"Confirmed",
        country: "India",
        email: "aryaveer@gmail.com",
        mobileNo: "9453693219",
        billingCityName: "Shivank street",
        billingBuildingName: "plam street",
        billingBlockName: "",
        billingFloorNo: "",
        billingUnit: "",
        billingPostalCode: "",
        billingStreetName: "",
        shippingPostalCode: "",
        shippingCityName: "",
        shippingBuildingName: "",
        shippingBlockName: "",
        shippingFloorNo: "",
        shippingunit: "",
        shippingStreetName: ""
    },
    {
        orderId: 1258,
        customerId: '1073',
        orderDate: "20/11/2022",
        orderNo: "DSR14500268",
        paymentStatus: "paid",
        deliveryType: "standard",
        paymentType: "Card",
        total: "$1482.14",
        deliveryStatus: "Confirmed",
        orderStatus:"Confirmed",
        country: "India",
        email: "aryaveer@gmail.com",
        mobileNo: "9453693219",
        billingCityName: "Shivank street",
        billingBuildingName: "plam street",
        billingBlockName: "",
        billingFloorNo: "",
        billingUnit: "",
        billingPostalCode: "",
        billingStreetName: "",
        shippingPostalCode: "",
        shippingCityName: "",
        shippingBuildingName: "",
        shippingBlockName: "",
        shippingFloorNo: "",
        shippingunit: "",
        shippingStreetName: ""
    },
]

export let cancelOrder = [
    {
        cancelTransId: 147,
        orderId: 128,
        total: "$1482.14",
        refundInitiated: false,
        productId: [142, 458, 369, 458],
        deliveryCharge: "$8.1"
    },
    {
        cancelTransId: 147,
        orderId: 1258,
        total: "$1482.14",
        refundInitiated: false,
        productId: [142, 458, 369, 458],
        deliveryCharge: "$8.1"
    },
    {
        cancelTransId: 142,
        orderId: 1258,
        total: "$1482.14",
        refundInitiated: false,
        productId: [142, 458, 369, 458],
        deliveryCharge: "$8.1"
    },
    {
        cancelTransId: 171,
        orderId: 1255,
        total: "$1482.14",
        refundInitiated: false,
        productId: [142, 458, 369, 458],
        deliveryCharge: "$8.1"
    }
]
export let orderTransactin = [
    {
        transactionId: "r1548268ef457",
        orderId: 1534,
        productId: [145, 254, 9875,],
        discount: "$4.24",
        deliveryCharge: "$8.125",
        productTotal: "$875.32",
        tax: "$48.45",
        totalAmountWith: "$587.41",
        methodOfPayment: "Cash"
    },
    {
        transactionId: "r1548268ef457",
        orderId: 1504,
        productId: [145, 254, 9875,],
        discount: "$4.24",
        deliveryCharge: "$8.125",
        productTotal: "$875.32",
        tax: "$48.45",
        totalAmountWith: "$587.41",
        methodOfPayment: "UPI"
    },
    {
        transactionId: "r1548268ef457",
        orderId: 1514,
        productId: [145, 254, 9875,],
        discount: "$4.24",
        deliveryCharge: "$8.125",
        productTotal: "$875.32",
        tax: "$48.45",
        totalAmountWith: "$587.41",
        methodOfPayment: "COD"
    },
    {
        transactionId: "r1548268ef457",
        orderId: 1569,
        productId: [145, 254, 9875,],
        discount: "$4.24",
        deliveryCharge: "$8.125",
        productTotal: "$875.32",
        tax: "$48.45",
        totalAmountWith: "$587.41",
        methodOfPayment: "Card"
    }
]